#!/bin/sh

################################################
## This is a grid-study, where the thickness of the
## AD is 2 cells.
##
## Grid level = 0: D/4
## Grid level = 1: D/8
## Grid level = 2: D/16
## Grid level = 3: D/32
################################################


# List of grid levels to be run
GRID_LEVELS="2"

# Loop over each grid level
for LEVEL in $GRID_LEVELS; do
    echo "Running grid level: $LEVEL"
    # Copy the clean folder to a new folder for this grid level
    cp -r clean case_grid${LEVEL}
    # Change to the new case directory
    cd case_grid${LEVEL}
    # Change the refinelvls value in setup file
    sed -i "" "s/^refinelvls.*/refinelvls            $LEVEL;/" setup
    # Now echo that we will run and run the case (Allrun script)
    echo "Running simulation for grid level $LEVEL..."
    ./Allrun
    cd ..
done



#------------------------------------------------------------------------------
