#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions:
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh

# Splitting domain:
runApplication decomposePar

# Refine grid in AD region
runParallel snappyHexMesh -overwrite

# Solving:
runParallel topoSet

runParallel $(getApplication)

# Reconstruction:
runApplication reconstructParMesh -constant
runApplication reconstructPar -constant

# Postprocess lines
runApplication postProcess -func lines -latestTime
mv log.postProcess log.postProcessLines

# Postprocess surfaces
runApplication postProcess -func surfaces -latestTime
mv log.postProcess log.postProcessSurfaces

# Post process and saving:
#runApplication foamLog log.simpleFoam
touch test.foam

#------------------------------------------------------------------------------
